# makefile to plot figures containing relative variance components
#
#
#
# python script for variance components plotting
VARCOMPPY=./varcomps_general.py
# python script for plotting the a coefficients
ACOEFFPY=./mean_a_plot.py

# python script for plotting the prestige versus conformism coefficients
HVCOEFFPY=./conformism_versus_prestige.py

# data file with the original analysis of variance components
DATAVARCOMP=../../data/summary_single_logistic.csv

# data file where only maternal effects are evolvingwhere only maternal effects are evolvingwhere only maternal effects are evolvingwhere only maternal effects are evolving
DATAVARCOMPMAT=../../data/summary_cue_int_posneg_mateffect_only.csv

EXT=pdf

.PHONY: clean

clean :
	rm -rf *.$(EXT)
